# Generated by Django 4.1.6 on 2023-02-07 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('datepublished', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
                ('imagethumbnail', models.ImageField(upload_to='articles/static/articles/images/post')),
                ('imagecaptions', models.CharField(blank=True, default='...', max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('nb_views', models.IntegerField(blank=True, default=0, null=True)),
                ('publishedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
