# Generated by Django 4.1.6 on 2023-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_imagethumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=60)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
